plugins {
    id 'java'
}

group = 'ru.khozain'
version = '1.0.0'

repositories {
    mavenCentral()
    maven {
        url = 'https://repo.papermc.io/repository/maven-public/'
    }
}

dependencies {
    compileOnly 'io.papermc.paper:paper-api:26.2.build.121-stable'
}

def targetJavaVersion = 25

tasks.withType(JavaCompile).configureEach {
    options.encoding = 'UTF-8'
    options.release.set(targetJavaVersion)
}

jar {
    archiveBaseName = 'inhGraphics'
}
